# Generated by Django 5.2.8 on 2025-11-30 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_comennt'),
    ]

    operations = [
        migrations.AddField(
            model_name='comennt',
            name='create_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='create_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='update_ad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
